import Landing from '@/components/Landing'
import fireDB from '@/firebase/initFirebase';
import { collection, getDocs } from 'firebase/firestore';
import Head from 'next/head'
import Layout from '../layout/Layout'


export async function getServerSideProps() {
  const firebaseRooms = await getDocs(collection(fireDB, "rooms"));
  const rooms: any = []
  firebaseRooms.forEach((doc) => {
    const obj = {
      id: doc.id,
      ...doc.data()
    }

    rooms.push(obj)
  });

  return {
    props: {
      rooms
    }
  }
}

export default function Home({ rooms }: any) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
  
      <Layout>
        <Landing rooms={rooms} />
      </Layout>
    </>
  )
}
